
CREATE TABLE [dbo].[Exercise]
(
	[ExerciseId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	ChestExercise VARCHAR(5000) NOT NULL,
	BackExercise VARCHAR(5000) NOT NULL,
	ShoulderExercise VARCHAR(5000) NOT NULL,
	BicepExercise VARCHAR(5000) NOT NULL,
	TricepExercise VARCHAR(5000) NOT NULL,
	LegExercise VARCHAR(5000) NOT NULL
)
