CREATE TABLE [dbo].[Nutrition]
(
	NutritionId UNIQUEIDENTIFIER PRIMARY KEY,
	[MealOne] VARCHAR(MAX) NOT NULL,
	[MealTwo] VARCHAR(MAX) NOT NULL,
	[MealThree] VARCHAR(MAX) NOT NULL, 
    [MealFour] VARCHAR(MAX) NOT NULL, 
    [MealFive] VARCHAR(MAX) NOT NULL, 
    [MealSix] VARCHAR(MAX) NOT NULL,
)
